"""initial migration

Revision ID: c2e86035e9a9
Revises: 
Create Date: 2024-01-20 23:14:51.233586

"""
from alembic import op
import sqlalchemy as sa

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e86035e9a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###

#
# # revision identifiers, used by Alembic.
# revision = 'c2e86035e9a9'
# down_revision = None
# branch_labels = None
# depends_on = None
#
#
# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('task', sa.Column('done', sa.Boolean(), nullable=True))
#     op.alter_column('task', 'description',
#                existing_type=sa.VARCHAR(length=300),
#                type_=sa.String(length=500),
#                nullable=True)
#     # ### end Alembic commands ###
#
#
# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.alter_column('task', 'description',
#                existing_type=sa.String(length=500),
#                type_=sa.VARCHAR(length=300),
#                nullable=False)
#     op.drop_column('task', 'done')
#     # ### end Alembic commands ###
